name: CI & Deploy Rust Worker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable
          target: wasm32-unknown-unknown

      - name: Install worker-build
        run: cargo install --locked worker-build

      - name: Build to Wasm
        run: worker-build --release

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: publish
